name: issue-notify

on:
  issues:
    types: [opend]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: get keyword
      id: get-keyword
      run: | 
        ehco level=Undefined >> $GITHUB_OUTPUT

        keywords=$(cat keyword-list.txt)
        for keyword in $keywords; do # 반복문 
          if [[ "${{ github.event.issue.title }}" =~ $keyword" ]]; then
            echo level=$keyword >> $GITHUB_OUTPUT
          fi
        done
    - name: get output
      run: |
        echo ${{ steps.get-keyword.outputs.level }}



        
